In [1]:
import numpy as np
# A numpy array is defined in the following manner where our number of rows are 3 and number of columns are 4 making it a 3x4 matrix
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

print(matrix.shape)

# You can even set your own shape, i.e. the dimensions of the numpy array. The dimensions should be the multiples of the total number of elements in the numpy array which is 12 in our case
matrix.shape = (2,6)
# Gives you a numpy array with 2 rows and 6 columns.
print("\n\nA 2x6 Matrix : ")
print(matrix)

(3, 4)


A 2x6 Matrix : 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [2]:
# arange will give you a numpy array of evenly spaced numbers of a one dimensional array and reshape the array by passing the dimensions
# We have created a 3-dimensional array here. ndim is used to get the number of dimension a numpy has
ndarray = np.array(np.arange(27),dtype = np.int32).reshape(3,3,3)
print("The array : ")
print(ndarray)

print("\n Number of dimensions : ",end = "")
print(ndarray.ndim)
# dtype we have used is the datatype of the elements of the array which is by default int32, i.e 32/8=4 bytes per element
print(ndarray.itemsize)

The array : 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 Number of dimensions : 3
4


In [3]:
# It will create an empty numpy array of dimensions mentioned and the datatype initialized
emptyArray = np.empty([4,4],dtype = int)
print(emptyArray)

[[   3801155    5701724    7209065    7274596]
 [   7536759    7536732    7536761    6619252]
 [   3342445    6029362    7536754    6619233]
 [   6815854    6553646    7077996 1667825664]]


In [4]:
type(np.zeros((20))[0])
# Creates numpy array of zeros
np.zeros((5),dtype = int)


array([0, 0, 0, 0, 0])

In [5]:
list = [1,2,3,4,5,6,7,8,9]
listOfTuples = [(1,2,3),(4,5,6),(7,8,9)]
numpyListArray = np.asarray(list)
numpyListTupleArray = np.asarray(listOfTuples)
print (numpyListArray)
print (numpyListTupleArray)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
string = 'Tejas Shinde'
# The letter 'b' is used to display the byte strings
np.frombuffer(b'Tejas Shinde' , dtype = 'S1')

array([b'T', b'e', b'j', b'a', b's', b' ', b'S', b'h', b'i', b'n', b'd',
       b'e'], dtype='|S1')

In [7]:
list = range(50)
iterator = iter(list)

# Using this iterator to create a numpy array FROM 0-50 which is the range given by us
iteratorArray = np.fromiter(iterator , dtype = int)
print(iteratorArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [8]:
print(np.linspace(10,20,12))

[10.         10.90909091 11.81818182 12.72727273 13.63636364 14.54545455
 15.45454545 16.36363636 17.27272727 18.18181818 19.09090909 20.        ]


In [9]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
print("Original Array : ")
print(array)
print("\n")

# Array of items in the second column
print("Array of items in the second column : ")
print (array[...,1])
print ("\n")

# Array of items from the first row
print("Array of items from the first row : ")
print(array[0,...])
print("\n")

# Array of items from column 2 onwards
print("Array of items from 2nd column onwards : ")
print(array[...,1:])

Original Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array of items in the second column : 
[2 5 8]


Array of items from the first row : 
[1 2 3]


Array of items from 2nd column onwards : 
[[2 3]
 [5 6]
 [8 9]]


In [10]:
list = ['Tejas','Prathamesh']
for iterator in list:
    if 'lcm' in iterator:
        print(iterator)
else:
    print("Negative")

Negative


In [11]:
from numpy import lcm,array
print(lcm.reduce((array([5,6,32,4,2,69,101]))))


1115040
